### ISSUE TITLE
How to set region of ECR repo?

### ISSUE THREAD

**Issue by benschwarz** [seek-oss/docker-ecr-publish-buildkite-plugin#13]
We have ECR repositories in multiple regions — how can we configure this plugin so that it pushes to a given region? 

Seeing as this plugin uses `aws` cli, I figured that we may be able to configure it as follows: 

```
- branches: stable
    label: ":ecr: Stable image (me-south-1)"
    env:
      AWS_DEFAULT_REGION: me-south-1
    plugins:
      - seek-oss/docker-ecr-publish#v1.2.0:
          ecr-name: calibre/reporter
          tags:
            - stable
```

This returns an error, stating: `An error occurred (RepositoryNotFoundException) when calling the DescribeRepositories operation: The repository with name 'calibre/reporter' does not exist in the registry with id '<account id removed from paste>`

**Comment by runk** [comment]
Hmmm. Should it be like 

```
- branches: stable
    label: ":ecr: Stable image (me-south-1)"

    plugins:
      - seek-oss/docker-ecr-publish#v1.2.0:
          ecr-name: calibre/reporter
          tags:
            - stable
          env:
            AWS_DEFAULT_REGION: me-south-1
```

?
