### ISSUE TITLE
Error using save-digest-as-metadata

### ISSUE THREAD

**Issue by NeelamAggarwal** [seek-oss/docker-ecr-publish-buildkite-plugin#32]
Error message:
```
--- Saving Docker image digest to Buildkite metadata: my-metadata-variable

/var/lib/buildkite-agent/plugins/github-com-seek-oss-docker-ecr-publish-buildkite-plugin-v2-4-0/hooks/command: line 229: image: unbound variable

[31mðŸš¨ Error: The command exited with status 1[0m
^^^ +++
^^^ +++
user command error: The plugin docker-ecr-publish command hook exited with status 1
~~~ Running global pre-exit hook
[90m$[0m /etc/buildkite-agent/hooks/pre-exit
~~~ Stopping ssh-agent 15751
```

Basic pipeline
```
steps:
  - plugins:
      - seek-oss/docker-ecr-publish#v2.5.0:
          ecr-name: e2e-smoke-tests
          save-digest-as-metadata: my-metadata-variable

```
@72636c
